### ISSUE TITLE
项目生成提示需要.Net9

### ISSUE THREAD

**Issue by Hjh9527** [842549829/Panda#2]
当前 .NET SDK 不支持面向 .NET 9.0。请面向 .NET 8.0 或更低版本，或者使用支持 .NET 9.0 的 .NET SDK 版本。

**Comment by 842549829** [comment]
由于测试项目依赖了.net9
在此次提交已经优化处理
https://github.com/842549829/Panda/commit/439ae875ce9db5322e3ca062bd0da86f298b33a4
